language: php
sudo: false
dist: xenial
php:
  - 7.2.16
  - nightly

env:
  - TRAVIS_NODE_VERSION="10"

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

addons:
  apt:
    packages:
      - nodejs

cache:
  apt: true
  directories:
    - $HOME/.composer/cache
    - $HOME/.yarn-cache
    - vendor

before_install:
  - composer self-update
  - export PATH=$HOME/.yarn/bin:$PATH && travis_retry curl -o- -L https://yarnpkg.com/install.sh | bash

install:
  - node -v && yarn -V
  - travis_retry yarn
  - composer install -o --prefer-dist --no-interaction

script:
  - yarn
  - yarn run "build:production"
